---
title: "Run Summary"
output: html_document
---

```{r setup, echo  = FALSE, warning = FALSE, message = FALSE}

library(tidyverse)
library(grid)
library(plotly)
df <- list.files(path=here::here("output/"),pattern = "*.csv",full.names = T) %>% 
  map_df(~data.table::fread(.,stringsAsFactors=F,check.names=T,strip.white=T))

test<- read.csv(here::here("output/output_20241120_145146.csv"))

df2<- df %>% dplyr::mutate(run_number = as.character(rep(1:(length(df$mode)/90), each = 90)))

cod_acl <- 99
had_acl <- 1075
```

## Management Measures

```{r,  echo  = FALSE, warning = FALSE, message = FALSE}
SQ_regulations <- read.csv(here::here("data-raw/SQ_regulations.csv")) %>% 
  dplyr::rename(Category = Var, 
                SQ = Val)
df3<- df2 %>% dplyr::filter(!Category %in% c("CV", "ntrips", "nchoiceoccasions","cod" , "had")) %>% 
  dplyr::select(Category, Value, run_number) %>% 
  dplyr::left_join(SQ_regulations, by = c("Category")) 

seas<- df3 %>% dplyr::filter(stringr::str_detect(Category, "Season")) %>% 
  tidyr::separate(Value, into = c("Value1", "Value2"), sep = " - ") %>% 
  tidyr::separate(SQ, into = c("SQ1", "SQ2"), sep = " - ") %>% 
  dplyr::mutate(Value = as.integer(lubridate::ymd(Value2)-lubridate::ymd(Value1)), 
                SQ = as.integer(lubridate::ymd(SQ2)-lubridate::ymd(SQ1))) %>% 
  dplyr::mutate(Diff_from_SQ = dplyr::case_when(Value < SQ ~ "Shorter_Season", TRUE ~ ""),
                Diff_from_SQ = dplyr::case_when(Value > SQ ~ "Longer_Season", TRUE ~ Diff_from_SQ), 
                Value = paste0(Value1, " - ", Value2)) %>% 
  dplyr::select(Category, Diff_from_SQ, run_number)
                  
bag<- df3 %>% dplyr::filter(stringr::str_detect(Category, "bag")) %>% 
  dplyr::mutate(Diff_from_SQ = dplyr::case_when(as.numeric(Value) < as.numeric(SQ) ~ "Smaller_bag", TRUE ~ ""),
                Diff_from_SQ = dplyr::case_when(as.numeric(Value) > as.numeric(SQ) ~ "Larger_bag", TRUE ~ Diff_from_SQ)) %>% 
  dplyr::select(Category, Diff_from_SQ, run_number)

size<- df3 %>% dplyr::filter(stringr::str_detect(Category, "size")) %>% 
  dplyr::mutate(Diff_from_SQ = dplyr::case_when(as.numeric(Value) < as.numeric(SQ) ~ "Smaller_min_length", TRUE ~ ""),
                Diff_from_SQ = dplyr::case_when(as.numeric(Value) > as.numeric(SQ) ~ "Larger_min_length", TRUE ~ Diff_from_SQ)) %>% 
  dplyr::select(Category, Diff_from_SQ, run_number)

df4<- rbind(seas, bag, size) %>% 
  tidyr::separate(Category, into =c("Species", "mode", "Var"), sep = "_") %>% 
  dplyr::select(!Var)


Regs_out <- df3 %>%
  dplyr::select(!SQ) %>% 
  dplyr::select(!Opt) %>% 
  tidyr::separate(Category, into =c("Species", "mode", "Var"), sep = "_") %>%
  tidyr::pivot_wider(names_from = Var, values_from = Value) %>%
      
      #tidyr::pivot_wider(names_from = Species, values_from = c(bag, size, Season)) %>%
  dplyr::left_join(df4, by = c("Species", "mode", "run_number")) %>% 
  dplyr::filter(!bag == 0) %>%
      dplyr::rename(Mode = mode,
                    `Bag Limit` = bag,
                    `Min Size (in)` = size) %>%
      tidyr::separate(Species, into = c("Species"), sep = "(?<=[A-Za-z])") %>%
      dplyr::mutate(Species = dplyr::recode(Species, "C" = "Cod", "H" = "Haddock"),
                    Mode = dplyr::recode(Mode, "FH" = "For Hire", "PR" = "Private")) %>% 
   dplyr::select(run_number, Species, Mode, `Bag Limit`, `Min Size (in)`, Season, Diff_from_SQ)
 DT::datatable(Regs_out)
```





## Plot all catch totals on one figure

```{r ,  echo  = FALSE, warning = FALSE, message = FALSE}
  
catch_all<- df2 %>% 
  dplyr::filter(catch_disposition %in% c("keep", "Discmortality"),
                number_weight == "Weight") %>%
  dplyr::group_by(run_number,  Category) %>%
  dplyr::summarise(Value = sum(as.numeric(Value))) %>%
  dplyr::group_by(run_number, Category) %>%
  dplyr::summarise(Value = median(Value)) %>% 
  tidyr::pivot_wider(names_from = Category, values_from = Value)

 catch_agg<- df2 %>%
      #predictions_out %>%
      dplyr::filter(catch_disposition %in% c("keep", "Discmortality"),
                    number_weight == "Weight") %>%
   
      dplyr::group_by(run_number, Category) %>%
      dplyr::summarise(Value = sum(as.numeric(Value))) %>%
   dplyr::mutate(Value = Value * 0.000454) %>%
      dplyr::mutate(under_acl = dplyr::case_when(Category == "cod" & Value <= cod_acl ~ 1, TRUE ~ 0),
                    under_acl = dplyr::case_when(Category == "had" & Value <= had_acl ~ 1, TRUE ~ under_acl)) %>%
      dplyr::group_by(run_number, Category) %>%
      dplyr::summarise(under_acl = sum(under_acl),
                       Value = median(Value)) %>% 
   tidyr::pivot_wider(names_from = Category, values_from = c(Value, under_acl))

p<- catch_agg %>% ggplot2::ggplot(aes(x = Value_cod, y = Value_had, label = run_number, color = under_acl_cod))+
   geom_point() +
   geom_text(aes(label=run_number, hjust=1, vjust=1))+
   #geom_text(aes(label=ifelse(Value_cod>cod_acl & Value_had > had_acl, as.character(run_number), ' '), hjust=1, vjust=1))+
   geom_vline( xintercept =cod_acl)+
   geom_hline( yintercept =had_acl)+
   scale_fill_brewer(palette="Dark2")+
   ggtitle("Cod and Haddock Mortality")+
   ylab("Total Haddock Mortality")+
   xlab("Total Cod Mortality")
   


 
fig<- ggplotly(p)

fig
#gridExtra::grid.arrange(fig1, fig2, ncol = 2)

```
### CV and Mortality

```{r ,  echo  = FALSE, warning = FALSE, message = FALSE}

welfare <-  df2 %>%
  dplyr::filter(Category %in% c("CV")) %>%
  dplyr::group_by(run_number, option, Category, draw_out) %>%
  dplyr::summarise(Value = sum(as.numeric(Value))) %>%
  dplyr::group_by(run_number,option, Category) %>%
  dplyr::summarise(CV = median(Value)) 
  
  
catch<- df2 %>% 
  dplyr::filter(catch_disposition %in% c("keep", "Discmortality"),
                number_weight == "Weight") %>%
  dplyr::group_by(run_number, option, Category, draw_out) %>%
  dplyr::summarise(Value = sum(as.numeric(Value))) %>%
  dplyr::group_by(run_number, option, Category) %>%
  dplyr::summarise(Value = median(Value)) %>% 
  tidyr::pivot_wider(names_from = Category, values_from = Value) %>% 
  dplyr::left_join(welfare) %>% 
  dplyr::select(!Category)

 p1<- catch %>% ggplot2::ggplot(aes(x = cod, y = CV, color = run_number))+
   geom_point() +
   geom_vline( xintercept =350000)+
   scale_fill_brewer(palette="Dark2")+
   ggtitle("Cod")+
   ylab("Consumer Surplus ($)")+
   xlab("Total Cod Mortality")+
   theme(legend.position = "none")

 p2<- catch %>% ggplot2::ggplot(aes(x = had, y = CV, color = run_number))+
   geom_point() +
   geom_vline( xintercept =1405000)+
   scale_fill_brewer(palette="Dark2")+
   ggtitle("Hadock")+
   ylab("Consumer Surplus ($)")+
   xlab("Total Haddock Mortality")+
   theme(legend.position = "none")

 
fig1<- ggplotly(p1)
fig2<- ggplotly(p2)
fig1
fig2
#gridExtra::grid.arrange(fig1, fig2, ncol = 2)

```

 # Add green highlight to runs that work

```{r,  echo  = FALSE, warning = FALSE, message = FALSE}
 DT::datatable(catch)
```








